FIND_PATH(OpenBLAS_INCLUDE_DIR HINTS $ENV{OpenBLAS_ROOT}/include
    NAMES lapacke.h PATHS ${Open_BLAS_INCLUDE_SEARCH_PATHS}
)

FIND_LIBRARY(OpenBLAS_LIB HINTS $ENV{OpenBLAS_ROOT}/lib
    NAMES openblas PATHS ${Open_BLAS_LIB_SEARCH_PATHS}
)

SET (OpenBLAS_FOUND FALSE)
if (OpenBLAS_INCLUDE_DIR AND OpenBLAS_LIB)
  SET (OpenBLAS_FOUND TRUE)
endif()
